export * from './IndividualChallenge';
export * from './Footer';
export * from './Nav';
export * from './Home';
export * from './Login';
export * from './MeetTheTeam';
export * from './ChallengesList';
export * from './Logout';
export * from './UserPage';
export * from './Solution';
// export * from './Search';
